In [2]:
# SVM model will be used here for model selection and prediction

In [3]:
#importing libraries
import numpy as np
import pandas as pd
import sklearn
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

In [4]:
# data collection

In [5]:
diabetes_data = pd.read_csv('diabetes.csv')

In [6]:
diabetes_data.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [7]:
diabetes_data.min(axis = 'rows')

Pregnancies                  0.000
Glucose                      0.000
BloodPressure                0.000
SkinThickness                0.000
Insulin                      0.000
BMI                          0.000
DiabetesPedigreeFunction     0.078
Age                         21.000
Outcome                      0.000
dtype: float64

In [8]:
diabetes_data.max(axis = 'rows')

Pregnancies                  17.00
Glucose                     199.00
BloodPressure               122.00
SkinThickness                99.00
Insulin                     846.00
BMI                          67.10
DiabetesPedigreeFunction      2.42
Age                          81.00
Outcome                       1.00
dtype: float64

In [9]:
diabetes_data['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [10]:
diabetes_data.groupby('Outcome').mean()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
Outcome,,,,,,,,
0,3.298000,109.980000,68.184000,19.664000,68.792000,30.304200,0.429734,31.190000
1,4.865672,141.257463,70.824627,22.164179,100.335821,35.142537,0.550500,37.067164

In [12]:
X = diabetes_data.drop('Outcome', axis=1)
Y = diabetes_data['Outcome']

In [13]:
print(X)

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6
1              1       85             66             29        0  26.6
2              8      183             64              0        0  23.3
3              1       89             66             23       94  28.1
4              0      137             40             35      168  43.1
..           ...      ...            ...            ...      ...   ...
763           10      101             76             48      180  32.9
764            2      122             70             27        0  36.8
765            5      121             72             23      112  26.2
766            1      126             60              0        0  30.1
767            1       93             70             31        0  30.4

     DiabetesPedigreeFunction  Age
0                       0.627   50
1                       0.351   31
2                       0.672   32
3                       0.167   21
4                       2.288   33
..                        ...  ...
763                     0.171   63
764                     0.340   27
765                     0.245   30
766                     0.349   47
767                     0.315   23

[768 rows x 8 columns]

In [14]:
print(Y)

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [15]:
# data ranges are different --> data standarization need --> to bring in common range

In [16]:
scaler = StandardScaler()
# scaler.fit(X)
# standardized_data = scaler.fit_transform(X)

In [19]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

standardized_data = scaler.fit_transform(X)

In [21]:
# separating features and target

X = diabetes_data.drop(columns='Outcome')

Y = diabetes_data['Outcome']

In [22]:
# now train test split is needed to feed in our model

In [23]:
Y.shape

(768,)

In [24]:
X_train,X_test,Y_train,Y_test = train_test_split(X, Y , test_size = 0.2 , stratify = Y ,random_state = 2)

In [25]:
Y_train.shape

(614,)

In [26]:
# training our m

In [27]:
classifier = svm.SVC(kernel = 'linear')

In [28]:
# now fitting our own data to the model

In [29]:
classifier.fit(X_train,Y_train)

SVC(kernel='linear')

In [31]:
# now mdoel accuracy will be checked

In [32]:
# accuracy score on training data
train_pred = classifier.predict(X_train)
train_accuracy = accuracy_score(train_pred , Y_train)
print(train_accuracy)

0.7833876221498371

In [33]:
# accuracy score on testing data
test_pred = classifier.predict(X_test)
test_accuracy = accuracy_score(test_pred , Y_test)
print(test_accuracy)

0.7727272727272727

In [34]:
# now making our own systems to check the model ------------------------------------------------------>

In [35]:
# we have to reshape the data --> as model expects whole data as input --> but we are providing only single instance

In [36]:
# as we have standardized data provided in our model -- > so we have to change it for input also
# std_data = scaler.transform(reshaped_data)

In [37]:

# lets create a func for our predict_system

In [38]:
def diabetes_prediction(arr):
    inp_data_as_nparray = np.asarray(arr)
    reshaped_data = inp_data_as_nparray.reshape(1,-1)
    # scaler.fit(reshaped_data)
    # std_data = scaler.fit_transform(reshaped_data)
    predict = classifier.predict(reshaped_data)
    return predict

In [39]:
input_data = (9,171,110,24,240,45.4,0.721,54)
diabetes_prediction(input_data)

c:\Users\DELL\OneDrive\Desktop\yensul\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(

array([1])

In [ ]:
# NOW WE WILL SAVE OUR MDOEL AND WILL USE IT FOR OTHER IMPLEMENTATION

In [ ]:
# pickle library

In [41]:
import pickle

In [40]:
file_name = 'trained_model.sav'

In [42]:
pickle.dump(classifier,open(file_name , 'wb'))

In [ ]:
# loading the model

In [43]:
loaded_model = pickle.load(open('trained_model.sav','rb'))